services:
  bcm-links:
    build:
      context: .
      args:
        KARAKEEP_VERSION: "0.32.0"
        MEILISEARCH_VERSION: "v1.41.0"
    image: bcm-links:0.32.0
    restart: no
    ports:
      - "3333:3000"
    env_file:
      - path: .links.env
        required: true
    volumes:
      - ../../../../storage/links/app:/data
      - ../../../../storage/links/search:/meili_data
