name: Dependencies

on:
  # Allow manual trigger via GitHub Repo
  workflow_dispatch:
  # Run automatically on a schedule
  schedule:
    # When to run this scheduled task
    #  - Run this workflow daily at 6am Sydney Time
    #  - This cron requires the UTC Time Zone
    #  - Sydney Time at 6am is the day before at 7pm in UTC Time
    #  - Review this timezone comparison at https://everytimezone.com/?t=69852f00,474
    #  - Review this cron expression at https://crontab.guru/#00_19_*_*_*
    - cron: "00 19 * * *"

permissions:
  contents: read

jobs:
  deps-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set build artifact name
        id: artifact
        shell: bash
        run: echo "artifact-file-name=build-$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
      - name: Update script file attributes
        shell: bash
        run: chmod +x ./bin/*.sh
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: latest
      - name: Setup environment
        shell: bash
        run: deno task setup
      - name: Build site
        shell: bash
        run: deno task build
      - name: Run deps-update
        shell: bash
        run: deno task deps-update
      - name: Check for changes
        id: changes
        shell: bash
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Git status found changes:"
            git status --porcelain
            echo "has_changes=true" >> "$GITHUB_OUTPUT"
          else
            echo "Git status didn't find changes:"
            git status --porcelain
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
          fi
      - name: Run tests
        if: steps.changes.outputs.has_changes == 'true'
        shell: bash
        run: deno task test
      - name: Run test
        shell: bash
        run: deno task test
      - name: Setup Git
        run: |
          git config user.name "bot-deps"
          git config user.email "bcm+bot-deps@murty.au"
          git config --global push.default current
      - name: Generate new branch name
        id: feature-branch
        run: echo "branch-name=deps-$(date +"%Y%m%d-%H%M%S")" >> $GITHUB_OUTPUT
      - name: Create new branch
        run: |
          git checkout main
          git pull origin main
          git checkout -b ${{ steps.feature-branch.outputs.branch-name }}
      - name: Create commit
        run: |
          git add deno.json
          git add deno.lock
          git commit -m "deps: Upgrade dependencies"
      - name: Push feature branch
        run: git push -u origin ${{ steps.feature-branch.outputs.branch-name }}
      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base main \
            --head ${{ steps.feature-branch.outputs.branch-name }} \
            --title "bot-deps: Update dependencies [${{ steps.feature-branch.outputs.branch-name }}]" \
            --body "These changes were generated by a run of the [dependencies workflow](https://github.com/bmurty/site/actions/workflows/dependencies.yml)." \
            --label "bot" \
            --label "deps" \
            --assignee "bmurty" \
