name: Dependencies

on:
  # Allow manual trigger via GitHub Repo
  workflow_dispatch:
  # Run automatically on a schedule
  schedule:
    # When to run this scheduled task
    #  - Run this workflow daily at 6am Sydney Time
    #  - This cron requires the UTC Time Zone
    #  - Sydney Time at 6am is the day before at 7pm in UTC Time
    #  - Review this timezone comparison at https://everytimezone.com/?t=69852f00,474
    #  - Review this cron expression at https://crontab.guru/#00_19_*_*_*
    - cron: "00 19 * * *"

permissions:
  contents: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deps-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Update script file attributes
        shell: bash
        run: chmod +x ./bin/*.sh
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: latest
      - name: Setup environment
        run: deno task setup
      - name: Run deps-update
        run: deno task deps-update
      - name: Check for changes
        id: check
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Git status found changes."
            echo "has_changes=true" >> "$GITHUB_OUTPUT"
          else
            echo "Git status didn't find changes."
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
          fi
      - name: Build site
        if: steps.check.outputs.has_changes == 'true'
        run: deno task build
      - name: Run tests
        if: steps.check.outputs.has_changes == 'true'
        run: deno task test
      - name: Commit and push feature branch
        if: steps.check.outputs.has_changes == 'true'
        run: |
          git config user.name "bot-deps"
          git config user.email "bcm+bot-deps@murty.au"
          git config --global push.default current
          git checkout -b deps-${{ github.run_id }}
          git add deno.json
          git add deno.lock
          git commit -m "bot-deps: Upgrade dependencies"
          git push -u origin deps-${{ github.run_id }}
      - name: Create Pull Request
        if: steps.check.outputs.has_changes == 'true'
        run: |
          gh pr create \
            --base main \
            --head deps-${{ github.run_id }} \
            --title "bot-deps: Update dependencies [deps-${{ github.run_id }}]" \
            --body "This PR was generated by a [Dependencies workflow run](https://github.com/bmurty/site/actions/runs/${{ github.run_id }})." \
            --label "bot" \
            --label "deps" \
            --assignee "bmurty" \
