name: Dependency Update
run-name: "Dependency Update - Branch ${{ github.ref_name }}, commit ${{ github.sha }}"

#
#
# ----
# Scheduled Workflow: Dependency Update
# ----
#
# This is a custom scheduled workflow to automate the update process of third-party dependencies
#
# ----
#
# Initial setup:
#
#  - Setup a new classic Personal Access Token via https://github.com/settings/tokens
#    - This token requires both `repo` and `workflow` scopes
#    - Copy the token value when prompted
#  - Create a new GitHub Repository Secret via Repo > Settings > Secrets > Actions
#    - Name it `BOT_GITHUB_TOKEN`
#    - For the value, use the Personal Access Token you copied from above
#    - The PR creation step here needs this PAT in order to create draft PRs that can then run other workflows
#
#

on:
  # Allow manual triggers via GitHub Repo > Actions > Release
  workflow_dispatch:
  # Run automatically on a schedule
  schedule:
    # When to run this scheduled task
    #  - Run this workflow daily at 6am Sydney Time
    #  - This cron requires the UTC Time Zone
    #  - Sydney Time at 6am is the day before at 7pm in UTC Time
    #  - Review this timezone comparison at https://everytimezone.com/?t=69852f00,474
    #  - Review this cron expression at https://crontab.guru/#00_19_*_*_*
    - cron: "00 19 * * *"

permissions:
  contents: write
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deps-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Update script file attributes
        shell: bash
        run: chmod +x ./bin/*.sh
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: latest
      - name: Setup environment
        run: deno task setup
      - name: Run deps-update
        run: deno task deps-update
      - name: Check for changes
        id: check
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Git status found changes."
            echo "has_changes=true" >> "$GITHUB_OUTPUT"
          else
            echo "Git status didn't find changes."
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
          fi
      - name: Build site
        if: steps.check.outputs.has_changes == 'true'
        run: deno task build
      - name: Run tests
        if: steps.check.outputs.has_changes == 'true'
        run: deno task test
      - name: Commit and push feature branch
        if: steps.check.outputs.has_changes == 'true'
        id: commit
        run: |
          BRANCH_NAME="deps-${{ github.run_id }}"
          git config user.name "bot-dependency-update"
          git config user.email "bcm+bot-deps@murty.au"
          git checkout develop
          git checkout -b "$BRANCH_NAME"
          git add deno.json
          git add deno.lock
          git commit -m "Dependency Update"
          git push -u origin "$BRANCH_NAME"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
      - name: Create Pull Request
        if: steps.check.outputs.has_changes == 'true'
        env:
          GH_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
        run: |
          gh pr create \
            --head "${{ steps.commit.outputs.branch_name }}" \
            --base develop \
            --title "Dependency Updates - deps-${{ github.run_id }}" \
            --body "Automated [dependency update](https://github.com/bmurty/site/actions/runs/${{ github.run_id }})." \
            --label "bot" \
            --label "deps" \
            --assignee "bmurty" \
