name: Release

on:
  push:
    tags:
      - "[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9].[0-9][0-9][0-9][0-9]"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DENO_DEPLOY_ORG: ${{ secrets.DENO_DEPLOY_ORG }}
  DENO_DEPLOY_PROJECT: ${{ secrets.DENO_DEPLOY_PROJECT }}
  DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Build site
        id: build-site
        uses: ./.github/actions/build-site
      - name: Download build files
        uses: actions/download-artifact@v7
        with:
          name: ${{ steps.build-site.outputs.artifact-file-name }}
      - name: Run tests
        shell: bash
        run: deno task test

  deploy:
    name: Deploy
    needs: test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Download build files
        uses: actions/download-artifact@v7
        with:
          name: ${{ steps.build-site.outputs.artifact-file-name }}
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: latest
      - name: Deploy to Deno Deploy
        run: |
          deno deploy \
            --org=$DENO_DEPLOY_ORG \
            --app=$DENO_DEPLOY_PROJECT \
            --token=$DENO_DEPLOY_TOKEN \
            --static=_site \
            --prod

  release:
    name: Release
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Generate release notes
        run: bash 'dev/release-notes.sh' 'release-notes.log'
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
          bodyFile: release-notes.log
          makeLatest: true
      - name: Cleanup
        run: rm release-notes.log
