name: Release

on:
  # Allow manual trigger via GitHub Repo
  workflow_dispatch:
    inputs:
      confirmation_phrase:
        description: 'To deploy to production, type DEPLOY in lowercase.'
        type: string
        required: true
  # Automatically trigger on push of a release tag
  push:
    tags:
      - "[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9].[0-9][0-9][0-9][0-9]"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DENO_DEPLOY_ORG: ${{ secrets.DENO_DEPLOY_ORG }}
  DENO_DEPLOY_PROJECT: ${{ secrets.DENO_DEPLOY_PROJECT }}
  DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}

permissions:
  contents: read

jobs:
  prepare:
    name: Prepare
    if: ${{ github.event.inputs.confirmation_phrase == 'deploy' }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate release tag
        id: release
        run: echo "tag-name=release-$(date +%Y%m%d.%H%M)" >> $GITHUB_OUTPUT

  build:
    name: Build
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Set build artifact name
        id: artifact
        shell: bash
        run: echo "artifact_name=build-$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
      - name: Update script file attributes
        shell: bash
        run: chmod +x ./bin/*.sh
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: latest
      - name: Setup environment
        shell: bash
        run: deno task setup
      - name: Build site
        shell: bash
        run: deno task build
      - name: Upload build files
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.artifact.outputs.artifact_name }}
          overwrite: true
          include-hidden-files: true
          retention-days: 1
          compression-level: 9
          path: |
            _site/
            .env

  test:
    name: Test
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Download build files
        uses: actions/download-artifact@v8
        with:
          name: ${{ steps.artifact.outputs.artifact_name }}
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: latest
      - name: Run tests
        shell: bash
        run: deno task test

  deploy:
    name: Deploy
    needs: [build, test]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Download build files
        uses: actions/download-artifact@v8
        with:
          name: ${{ steps.artifact.outputs.artifact_name }}
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: latest
      - name: Deploy to Deno Deploy
        run: |
          deno deploy \
            --org=$DENO_DEPLOY_ORG \
            --app=$DENO_DEPLOY_PROJECT \
            --token=$DENO_DEPLOY_TOKEN \
            --prod

  release:
    name: Release
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Create and push release tag
        run: |
          git config user.name "bot-release"
          git config user.email "bcm+bot-release@murty.au"
          git tag ${{ steps.release.outputs.tag_name }}
          git push --tags --quiet
      - name: Generate release notes
        run: bash 'bin/release-notes.sh' 'release-notes.log'
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ steps.release.outputs.tag_name }}
          tag: ${{ steps.release.outputs.tag_name }}
          bodyFile: release-notes.log
          makeLatest: true
      - name: Cleanup
        run: |
          rm release-notes.log
          rm .env
          rm -rf _site
